# Generated by Django 3.1.7 on 2021-02-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cave', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='cave.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='str', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='john', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='str', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='ussername',
            field=models.CharField(default='john12', max_length=100),
        ),
    ]
