# Generated by Django 3.1.7 on 2021-03-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cave', '0005_auto_20210303_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
